### ISSUE TITLE
Model latency numbers include time taken to retry

### ISSUE THREAD

**Issue by saikatmitra91** [empirical-run/empirical#166]
### 📝 Description
Since the model calls are wrapped by SDK and the SDK internally retries, the latency time calculation includes the total time taken to get the response and not the time taken by the final request to resolve. 

### 📸 Screenshots / Code Snippets
<img width="607" alt="Screenshot 2024-04-21 at 11 41 36 AM" src="https://github.com/empirical-run/empirical/assets/10416686/6b1ee12b-4f63-4d0d-b65d-838cb9576dbf">

### 🛠 Proposed Solution
- reset the timer when doing a retry

**Comment by sumitd94** [comment]
@saikatmitra91 I would like to work on this, can you please assign this to me?

**Comment by arjunattam** [comment]
Fixed with #216. Closing.
