### ISSUE TITLE
[chatbot example] - CLI summary doesnt show the second score - `personal`

### ISSUE THREAD

**Issue by saikatmitra91** [empirical-run/empirical#167]
### 📝 Description
The chatbot example contains 2 types of scorer. The first run configured uses just one scorer but the second run contains 2 scorers. The second score doesnt appear in cli report. The second score is shown in ui - webapp report.

<img width="860" alt="Screenshot 2024-04-22 at 7 52 10 AM" src="https://github.com/empirical-run/empirical/assets/10416686/37a8d32a-8c19-4fa0-91bc-75cfc9b349b1">
CLI report 

<img width="1717" alt="Screenshot 2024-04-22 at 7 53 52 AM" src="https://github.com/empirical-run/empirical/assets/10416686/c12fbaa7-8828-4f53-8fef-56fb45dd897e">

UI - webapp report ☝️ 

If you see above the CLI report has a missing "personal" scorer.

### 📸 Screenshots / Code Snippets
<img width="1265" alt="Screenshot 2024-04-22 at 7 50 42 AM" src="https://github.com/empirical-run/empirical/assets/10416686/ef4a176b-fcd3-442e-99d5-bb33cb7754f7">

**Comment by mukeshblackhat** [comment]
is this we want to get in the cli which is not their ? @saikatmitra91 

<img width="732" alt="Screenshot 2024-04-30 at 7 46 14 PM" src="https://github.com/empirical-run/empirical/assets/59144700/8ddc02d4-f0ce-420d-a553-a368de6935a1">

**Comment by saikatmitra91** [comment]
@mukeshblackhat 
I think if we havent assigned any scorer to a particular run, we should keep the cell as empty or `-`.
0% is misleading. It feels we assigned a scorer "personal" and got 0%.

**Comment by mukeshblackhat** [comment]
<img width="698" alt="Screenshot 2024-05-01 at 11 01 18 AM" src="https://github.com/empirical-run/empirical/assets/59144700/c827f48e-095d-4c12-9157-242d7d11326b">
![Screenshot 2024-05-01 at 11 01 04 AM](https://github.com/empirical-run/empirical/assets/59144700/60682a91-0506-4ae9-81c6-7b2067226d03)
is it not right ?
