### ISSUE TITLE
rag example: add run -> change parameter `model` to `gpt-4` -> script times out but no error shown on the UI

### ISSUE THREAD

**Issue by saikatmitra91** [empirical-run/empirical#168]
### 📝 Description
In the [RAG example](https://github.com/empirical-run/empirical/tree/main/examples/rag), change the parameter `model` to `gpt-4` and try running it. 

You would see the script times out but the UI - webapp - doesnt show any error. 

<img width="553" alt="Screenshot 2024-04-22 at 8 12 34 AM" src="https://github.com/empirical-run/empirical/assets/10416686/e6067667-2b3e-4b6c-a789-632f2a50ec8a">

### Expected
- an error in each output cell should mention that the `script timed out`.

**Comment by aditya-67** [comment]
@saikatmitra91 I tried this and was able to run `gpt-4` without any `script timed out` error. Is this a one-off error? Wasn't able to reproduce it.

`empiricalrc.json`

<img width="598" alt="Screenshot 2024-05-16 at 09 22 27" src="https://github.com/empirical-run/empirical/assets/9695866/1b9b465f-fbfb-4e11-8846-363b4700052c">


`Terminal`

<img width="613" alt="Screenshot 2024-05-16 at 09 22 52" src="https://github.com/empirical-run/empirical/assets/9695866/9944fb54-fe6b-479f-a108-e93a9d58787a">

**Comment by arjunattam** [comment]
Yes this is fixed with #183. Closing
